wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
alpha:
  desc: null
  value: 0.2
batch_size:
  desc: null
  value: 256
env_name:
  desc: null
  value: InvertedPendulumBulletEnv-v0
gamma:
  desc: null
  value: 0.99
layer1_size:
  desc: null
  value: 256
layer2_size:
  desc: null
  value: 256
lr:
  desc: null
  value: 0.001
max_size:
  desc: null
  value: 1000000
n_games:
  desc: null
  value: 250
reward_scale:
  desc: null
  value: 2
tau:
  desc: null
  value: 0.005
