wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
batch_size:
  desc: null
  value: 128
env_name:
  desc: null
  value: InvertedPendulumBulletEnv-v0
kernels:
  desc: null
  value:
  - 16
  - 32
learning_rate:
  desc: null
  value: 0.005
n_games:
  desc: null
  value: 250
